"""Knowledge-base search tool.

Demo scope: full-text search only (Postgres tsvector, already generated by
the schema). The `embedding VECTOR(1024)` column and hybrid fusion are in
the schema and architecture doc for when there's real content volume and
VOYAGE_API_KEY is wired up (scripts/index_knowledge.py) — not needed to
answer 6 policy docs well today. Swapping this function's internals later
doesn't change the tool's interface, so nothing upstream has to change.
"""

from __future__ import annotations

from psycopg.rows import dict_row

from src.db.connection import get_conn


def search_knowledge(query: str, limit: int = 3) -> dict:
    """Full-text search over knowledge_docs (policies, guides, FAQs)."""
    with get_conn() as conn, conn.cursor(row_factory=dict_row) as cur:
        # OR the query's lexemes rather than AND them (websearch_to_tsquery/
        # plainto_tsquery AND every term, which fails natural-language
        # questions the moment one word — e.g. "know", "how" — isn't in the
        # doc). Ranking still favors docs matching more terms.
        cur.execute(
            """
            WITH q AS (
                SELECT to_tsquery(
                    'english',
                    string_agg(lexeme, ' | ')
                ) AS tsq
                FROM unnest(tsvector_to_array(to_tsvector('english', %s))) AS lexeme
            )
            SELECT title, category, content, ts_rank(content_tsv, q.tsq) AS rank
            FROM knowledge_docs, q
            WHERE q.tsq IS NOT NULL AND content_tsv @@ q.tsq
            ORDER BY rank DESC
            LIMIT %s
            """,
            (query, limit),
        )
        rows = cur.fetchall()

    if not rows:
        # Fall back to trigram-ish loose match on title/category so a
        # slightly-off query (e.g. "resizing" vs "sizing") still finds something
        # rather than returning nothing for the demo.
        with get_conn() as conn, conn.cursor(row_factory=dict_row) as cur:
            cur.execute(
                """
                SELECT title, category, content, 0.0 AS rank
                FROM knowledge_docs
                WHERE title ILIKE %s OR category ILIKE %s
                LIMIT %s
                """,
                (f"%{query}%", f"%{query}%", limit),
            )
            rows = cur.fetchall()

    return {
        "results": [
            {"title": r["title"], "category": r["category"], "content": r["content"]}
            for r in rows
        ]
    }
